### ISSUE TITLE
overriding isBack screen

### ISSUE THREAD

**Issue by JClutch** [AZZB/react-native-swipe-navigation#1]
Was wondering if there was any way to override the checking for isBack=true on swiping?

The case being lets say I have a screen with a bottom, left, and right screen connected to it with your navigation. If I wanted to connect the right screen to the bottom screen so my users would only have to swipe once instead of twice to make that movement I would just add it in the navigation as the bottom of right as well. The problem is though when starting at the center --> Swiping right --> and swipe down to bottom screen, if I was to swipe up at this point it would not take me back to the center screen but would take me back to the screen on right because isBack is true and it considers the right screen to be the main. 

Is there any way to override this so I could follow this movement pattern but then allow the user to swipe up to the center screen instead of to the right?

**Comment by AZZB** [comment]
Actually you can't !
and it's not about overriding isBack because isBack is just an indication that let us know if we are navigating back or not but the the idea is that we are pushing in the stack when we navigate and popping from the stack when we navigate back so for example if we have screen A as the main screen and B is the right , C is the bottom of A and B (like you said) then the stack will be like this [A] , now if we navigate Right then the B will be pushed in the stack [A, B], also the same if we navigate Bottom the stack will be [A, B, C], and now if we navigate back then we will pop from the stack -> [A, B] so you will be in the screen B not A.

so in the summary maybe I have to provide replace method in nav prop api .

**Comment by JClutch** [comment]
Ahh I see.... is there a simple way to possibly reset the stack then as you're able to with StackNavigation? For reasons related to this but also performant reasons as well.

p.s. want to say thank you for this NPM module as it has been the best cross platform swiping we found for our app.



//Figured it out... going to make a pull request with the changes if you'd like
